<?php

$cities = array(
    array("'s-Hertogenbosch","'s-Hertogenbosch","Oeteldonk"),
    array("Aalst","Waalre","Ballengat"),
    array("Aarle-Rixtel","Laarbeek","Ganzegat"),
    array("Achtmaal","Zundert","Goudpoeperslaand"),
    array("Alphen","Alphen-Chaam","Struivenlaand"),
    array("Asten","Asten","Klotland"),
    array("Baarle-Nassau","Baarle-Nassau","Smokkelgat"),
    array("Baarschot","Hilvarenbeek","Knopspeldjesrijk"),
    array("Bakel","Gemert-Bakel","Pierewaaiersrijk"),
    array("Bavel","Breda","Baviaonenland"),
    array("Beek en Donk","Laarbeek","Ganzendonck"),
    array("Beers","Cuijk","Bokkerijersriek"),
    array("Bergen op Zoom","Bergen op Zoom","Krabbegat"),
    array("Berghem","Oss","Knollenrijk"),
    array("Berkel-Enschot","Tilburg","Knollevretersgat"),
    array("Berlicum","Sint-Michielsgestel","Dun Birrekoal"),
    array("Best","Best","Klompengat"),
    array("Beugen","Boxmeer","Verkeskop"),
    array("Biezenmortel","Haaren","Kleuvendurp"),
    array("Bladel","Bladel","Muggehol"),
    array("Boekel","Boekel","KnÃ¶llekesland"),
    array("Boerdonk","Veghel","Zandhazenrijk"),
    array("Borkel en Schaft","Valkenswaard","Mulkgat"),
    array("Bosschenhoofd","Halderberge","SmoorfrÃªterslaand"),
    array("Boxmeer","Boxmeer","Geitenbok"),
    array("Boxtel","Boxtel","Eendengat"),
    array("Breda","Breda","Kielegat"),
    array("Breugel","Son en Breugel","Krutjesgat"),
    array("Brouwhuis","Helmond","Brouwhazenrijk"),
    array("Budel-Dorplein","Cranendonck","Heiknuuterrijk"),
    array("Budel-Schoot","Cranendonck","Toeterland"),
    array("Budel","Cranendonck","Bokkenriek"),
    array("Capelle","Waalwijk","Cuppelsgat"),
    array("Casteren","Bladel","Bollemeppersgat"),
    array("Chaam","Alphen-Chaam","Bonenpikkerslaand"),
    array("Cromvoirt","Vught","Kneutergat"),
    array("Cuijk","Cuijk","NÃ¶lersriek"),
    array("De Heen","Steenbergen","Strienedurpke"),
    array("De Moer","Loon op Zand","MoerbiÃ«nlaand"),
    array("De Mortel","Gemert-Bakel","Krulstarteland"),
    array("De Rips","Gemert-Bakel","Streupersrijk"),
    array("Demen","Oss","Schottelzakkenrijk"),
    array("Den Dungen","Sint-Michielsgestel","Krabberdonk"),
    array("Den Hout","Oosterhout","Kluivenduikersrijk"),
    array("Dennenburg","Oss","Schottelzakkenrijk"),
    array("Deurne","Deurne","Peelstrekelrijk"),
    array("Deursen","Oss","Schottelzakkenrijk"),
    array("Dieden","Oss","Schottelzakkenrijk"),
    array("Diessen","Hilvarenbeek","Stopnaoldenrijk"),
    array("Dinteloord","Steenbergen","PeejlÃ²Ã²fdurp"),
    array("Dommelen","Valkenswaard","Brouwersgat"),
    array("Dongen","Dongen","Peejenrijk"),
    array("Dorst","Oosterhout","Kattegat"),
    array("Drunen","Heusden","DwergoniÃ«"),
    array("Duizel","Eersel","Zwetsland"),
    array("Dussen","Werkendam","Klaiendam"),
    array("Eerde","Veghel","Oiversland"),
    array("Eersel","Eersel","Buurtgat"),
    array("Eindhoven","Eindhoven","Lampegat"),
    array("Elsendorp","Gemert-Bakel","Peelvruutersrijk"),
    array("Elshout","Heusden","Zaandhaozenlaand"),
    array("Empel","'s-Hertogenbosch","Slotgat"),
    array("Engelen","â€™s-Hertogenbosch","Terpersdurp"),
    array("Erp","Veghel","Empeldonk"),
    array("Esbeek","Hilvarenbeek","Haaikneuterrijk"),
    array("Escharen","Grave","De Erpelkuul"),
    array("Esch","Haaren","Oggelvorsenpoel"),
    array("Etten","Etten-Leur","Stijlorenrijk"),
    array("Fijnaart","Moerdijk","'t Kleigat"),
    array("Galder","Alphen-Chaam","Maerkrattenland"),
    array("Gassel","Grave","Ezelrijk"),
    array("Gastel","Cranendonck","Pintewippersrijk"),
    array("Geertruidenberg","Geertruidenberg","Potteschijtersland"),
    array("Geffen","Oss","Rottenrijk"),
    array("Geldrop","Geldrop-Mierlo","Lappegat"),
    array("Gemert","Gemert-Bakel","Waeverstadt"),
    array("Gemonde","Sint-Michielsgestel","Mullukzuipertjesland"),
    array("Gerwen","Nuenen, Gerwen en Nederwetten","Narregat"),
    array("Gilze","Gilze en Rijen","Dringersgat"),
    array("Goirle","Goirle","Ballefruttersgat"),
    array("Grave","Grave","Pothuusburg"),
    array("Haagse Beemden","Breda","Giegeldonk"),
    array("Haaren","Haaren","Struivendurp"),
    array("Haarsteeg","Heusden","Haorendam"),
    array("Haghorst","Hilvarenbeek","Durdauwersgat"),
    array("Halsteren","Bergen op Zoom","Altere"),
    array("Handel","Gemert-Bakel","Bergkneuterrijk"),
    array("Hank","Boxmeer","Knusterooiersland"),
    array("Hank","Werkendam","Knusterooiersland"),
    array("Hapert","Bladel","Pintewippersrijk"),
    array("Haps","Cuijk","Dun Zelfkant Hops"),
    array("Haren","Oss","Knorreland"),
    array("Heerle","Roosendaal","Puitenlaand"),
    array("Heesch","Bernheze","Krullendonk"),
    array("Heeswijk-Dinther","Bernheze","Snevelbokkenland"),
    array("Heeze","Heeze-Leende","Kraaienland"),
    array("Helenaveen","Deurne","Peelpluimenrijk"),
    array("Helmond","Helmond","Kattegat"),
    array("Helvoirt","Haaren","Keiespellersdurp"),
    array("Helwijk","Moerdijk","Kiekendonk"),
    array("Herpen","Oss","BÃ´nnerijk"),
    array("Herpt","Heusden","Maoskesdam"),
    array("Heukelom","Oisterwijk","De Rommelpot"),
    array("Heusden","Asten","Peelvrujtersland"),
    array("Heusden","Heusden","Wallepoepersland"),
    array("Hilvarenbeek","Hilvarenbeek","Pezerikkengat"),
    array("Hintham","'s-Hertogenbosch","Oetelhoazendam"),
    array("Hoeven","Halderberge","Peejenland"),
    array("Hooge Mierde","Reusel-De Mierden","Haoiboerenrijk"),
    array("Hooge Zwaluwe","Drimmelen","Berenland"),
    array("Hoogeloon","Bladel","Lappelekkursland"),
    array("Hoogerheide","Woensdrecht","Wjeeldrecht"),
    array("Huijbergen","Woensdrecht","'t Sanegat"),
    array("Hulten","Gilze en Rijen","Krimpersgat"),
    array("Kaatsheuvel","Loon op Zand","Turfstekerslaand"),
    array("Keent","Oss","Nachtgraversrijk"),
    array("Keldonk","Veghel","Paplippelland"),
    array("Klundert","Moerdijk","Loerendonck"),
    array("Knegsel","Eersel","Klein Antwerpen"),
    array("Kruisland","Steenbergen","Pompedurp"),
    array("Kruisstraat","Roosendaal","'t Waoterhazenrijk"),
    array("Lage Mierde","Reusel-De Mierden","Peperbussenrijk"),
    array("Lage Zwaluwe","Drimmelen","Biesboschrakkersrijk"),
    array("Langenboom","Mill en Sint Hubert","Verkuskopperiek"),
    array("Langeweg","Moerdijk","Slikgat"),
    array("Leende","Heeze-Leende","Blaosdonk"),
    array("Lennisheuvel","Boxtel","Indegat"),
    array("Lepelstraat","Bergen op Zoom","Spoonstreet"),
    array("Leur","Etten-Leur","Zwaajgat"),
    array("Liempde","Boxtel","Ploegersland"),
    array("Lierop","Someren","Kaauwvoetenland"),
    array("Lieshout","Laarbeek","Raopersgat"),
    array("Liessel","Deurne","Keienland"),
    array("Lithoijen","Oss","VÃ¨rrekens"),
    array("Lith","Oss","Veldhazenrijk"),
    array("Loon op Zand","Loon op Zand","Theebuikenland"),
    array("Loosbroek","Bernheze","Zandkruiersland"),
    array("Luyksgestel","Bergeijk","'t Stekkegat"),
    array("Maarheeze","Cranendonck","Muuzegat"),
    array("Maashees","Boxmeer","De Bliekers"),
    array("Maaskantje","Sint-Michielsgestel","Krabberdonk"),
    array("Macharen","Oss","Kiepenrijk"),
    array("Made","Drimmelen","De May"),
    array("Maren-Kessel","Oss","Kleidonk"),
    array("Mariaheide","Veghel","Heikrikkeldurp"),
    array("Mariahout","Laarbeek","'t Heidurp"),
    array("Megen","Oss","Keiendonk"),
    array("Middelbeers","Oirschot","Strijkersgat"),
    array("Mierlo-Hout","Helmond","Kluppelland"),
    array("Mierlo","Geldrop-Mierlo","Kersenrijk"),
    array("Milheeze","Gemert-Bakel","Veenmollenrijk"),
    array("Mill","Mill en Sint Hubert","Germelaand"),
    array("Moerdijk","Moerdijk","Spieringkruiersdurp"),
    array("Moergestel","Oisterwijk","Pierewaaiersrijk"),
    array("Moerstraten","Roosendaal","Mangelpeejenlaand"),
    array("Molenschot","Gilze en Rijen","Papslokkersgat"),
    array("Nederwetten","Nuenen, Gerwen en Nederwetten","Wetterland"),
    array("Neerkant","Deurne","Ulewappersriek"),
    array("Neerlangel","Oss","Schottelzakkenrijk"),
    array("Neerloon","Oss","Nachtgraversrijk"),
    array("Netersel","Bladel","'t Hupke"),
    array("Nieuw-Vossemeer","Steenbergen","'t Vosse-ol"),
    array("Nieuwkuijk","Heusden","Kwastenlaand"),
    array("Nijnsel","Sint-Oedenrode","Papgat"),
    array("Nispen","Roosendaal","Aopelaand"),
    array("Nistelrode","Bernheze","Weversrijk"),
    array("Noordhoek","Moerdijk","Kantemaaiersgat"),
    array("Nuenen","Nuenen, Gerwen en Nederwetten","DwÃ¨rsklippelgat"),
    array("Nuland","'s-Hertogenbosch","Waoterrijk"),
    array("Odiliapeel","Uden","SchaopenWaeserland"),
    array("Oeffelt","Boxmeer","Leemkuul"),
    array("Oijen","Oss","Bokkenrijk"),
    array("Oirschot","Oirschot","SkÃ´n Orregat"),
    array("Oisterwijk","Oisterwijk","DÃ¶llekesgat"),
    array("Olland","Sint-Oedenrode","Papgat"),
    array("Ommel","Asten","R'Ommelpottersland"),
    array("Oosteind","Oosterhout","Uilendonck"),
    array("Oostelbeers","Oirschot","Strijkersgat"),
    array("Oosterhout","Oosterhout","Kaaiendonk"),
    array("Oploo","Sint Anthonis","Spurriebuukenriek"),
    array("Ossendrecht","Woensdrecht","Ostrecht"),
    array("Oss","Oss","Ossekoppenrijk"),
    array("Oud Gastel","Halderberge","Vastelaovedzottelaand"),
    array("Oudemolen","Moerdijk","Kleiknoestenstad"),
    array("Oudenbosch","Halderberge","Puitenol"),
    array("Overlangel","Oss","Nachtgraversrijk"),
    array("Overloon","Boxmeer","Huibuukeland"),
    array("Prinsenbeek","Breda","Boemeldonck"),
    array("Putte","Woensdrecht","Put en Buntland"),
    array("Raamsdonksveer","Geertruidenberg","Faantelaand"),
    array("Raamsdonk","Geertruidenberg","D'n Haaykaant"),
    array("Ravenstein","Oss","Pomperstad"),
    array("Reek","Landerd","Kelestreupersrijk"),
    array("Reusel","Reusel-De Mierden","Narrendonk"),
    array("Riel","Goirle","Kaaiengat"),
    array("Riethoven","Bergeijk","'t Bremspoersengat"),
    array("Rijen","Gilze en Rijen","Wringersgat"),
    array("Rijkevoort","Boxmeer","Blubberdam"),
    array("Rijsbergen","Zundert","Aopelaand"),
    array("Roosendaal","Roosendaal","Tullepetaonestad"),
    array("Rosmalen","'s-Hertogenbosch","Zandhazendurp"),
    array("Rucphen","Rucphen","Kraaierijk"),
    array("Sambeek","Boxmeer","Knoepersriek"),
    array("Schaijk","Landerd","Moesland"),
    array("Schijf","Rucphen","Torensjouwerslaand"),
    array("Schijndel","Schijndel","Schorsbos"),
    array("Sint Anthonis","Sint Anthonis","Zeikmeikenrijk"),
    array("Sint Hubert","Mill en Sint Hubert","Bokkenriek"),
    array("Sint-Michielsgestel","Sint-Michielsgestel","Bokkendonk"),
    array("Sint-Oedenrode","Sint-Oedenrode","Papgat"),
    array("Soerendonk","Cranendonck","Roesdonk"),
    array("Someren-Eind","Someren","De Plattevonder"),
    array("Someren-Heide","Someren","Land van de Keijepaol"),
    array("Someren","Someren","De Meerpoel"),
    array("Son","Son en Breugel","Krutjesgat"),
    array("Spoordonk","Oirschot","Olliedonk"),
    array("Sprundel","Rucphen","Nachtuilenrijk"),
    array("St. Willebrord","Rucphen","Heikneutersland"),
    array("Stampersgat","Halderberge","Meekrapdurp"),
    array("Standdaarbuiten","Moerdijk","Zwammegat"),
    array("Steenbergen","Steenbergen","Strienestad"),
    array("Steensel","Eersel","Pieregat"),
    array("Sterksel","Heeze-Leende","Osserijk"),
    array("Stevensbeek","Sint Anthonis","Snewbulten"),
    array("Stiphout","Helmond","Spurriezeiersland"),
    array("Teeffelen","Oss","Waoterrattenrijk"),
    array("Terheijden","Drimmelen","'t Schraansersrijk"),
    array("Teteringen","Breda","Totdenringen"),
    array("Tilburg","Tilburg","Kruikenstad"),
    array("Udenhout","Tilburg","D'n Haozenpot"),
    array("Uden","Uden","Knoerissenrijk"),
    array("Ulicoten","Baarle-Nassau","Haaikneuterslaand"),
    array("Ulvenhout","Breda","Bosuilendorp"),
    array("Valkenswaard","Valkenswaard","Striepersgat"),
    array("Veghel","Veghel","Kuussegat"),
    array("Veldhoven","Veldhoven","Rommelgat"),
    array("Velp","Grave","Zandkruiersrijk"),
    array("Venhorst","Boekel","'t Peeltuuterland"),
    array("Vessem","Eersel","Struifdonk"),
    array("Vianen","Cuijk","De Hei"),
    array("Vierlingsbeek","Boxmeer","'t Keieschietersriek"),
    array("Vinkel","'s-Hertogenbosch","Kafland"),
    array("Vinkel","Bernheze","Kafland"),
    array("Vlierden","Deurne","Dors'T'vlegelland"),
    array("Vlijmen","Heusden","Knotwilgendam"),
    array("Volkel","Uden","Pieperland"),
    array("Vorstenbosch","Bernheze","Piereslikkersrijk"),
    array("Vortum-Mullem","Boxmeer","De Plekkers"),
    array("Vught","Vught","Dommelbaorzedurp"),
    array("Waalre","Waalre","Keiengat"),
    array("Waalwijk","Waalwijk","Schoenlapperslaand"),
    array("Wagenberg","Drimmelen","Erpelrooierslaand"),
    array("Wanroij","Sint Anthonis","Paddenriek"),
    array("Waspik","Waalwijk","Maoneblusserslaand"),
    array("Welberg","Steenbergen","Raldal"),
    array("Wernhout","Zundert","Zaantaozelaant"),
    array("Westelbeers","Oirschot","Strijkersgat"),
    array("Westerbeek","Sint Anthonis","'t Tusriek"),
    array("Westerhoven","Bergeijk","'t Koffiegat"),
    array("Wijbosch","Schijndel","'t Weppus"),
    array("Wilbertoord","Mill en Sint Hubert","Klottenriek"),
    array("Willemstad","Moerdijk","Kakeldonk"),
    array("Wintelre","Eersel","Klepbroekenbult"),
    array("Woensdrecht","Woensdrecht","Wjeeldrecht"),
    array("Woudrichem","Woudrichem","Mosterdgat"),
    array("Wouwse Plantage","Roosendaal","Mastepinnelaand"),
    array("Wouw","Roosendaal","Paplaand"),
    array("Zeeland","Landerd","Smouzenrijk"),
    array("Zegge","Rucphen","Grasduinersdurp"),
    array("Zeilberg","Deurne","Pottenbakkersrijk"),
    array("Zevenbergen","Moerdijk","Zeuvebultelaand"),
    array("Zevenbergschen Hoek","Moerdijk","Snerkersdurp"),
    array("Zijtaart","Veghel","Reigerland"),
    array("Zundert","Zundert","Banaonblusserslaand")
);


for ($i=0;$i<count($cities);$i++) {
    $check = false;
    for ($k=0;$k<count($cities[$i]);$k++) {
        $carnavalName = $cities[$i][2];
        if (!$check) {
            if ($carnavalName[0] == "'") {
                echo $carnavalName . "<br>";
                $check = true;
            }
        }
    }
}


// complete
